# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orn', order.models.OrderNumber(max_length=20, verbose_name='定单号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pay_type', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '正在支付')], default=0, verbose_name='订单状态')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Course', verbose_name='课程')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 't_order_item',
            },
        ),
    ]
