# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程名')),
                ('summary', models.CharField(max_length=200, verbose_name='课程简介')),
                ('cover', models.CharField(max_length=200, verbose_name='封面url')),
                ('favor', models.IntegerField(default='0', verbose_name='点赞人数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='课程价格')),
                ('detail', models.CharField(max_length=300, verbose_name='课程详情url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 't_course',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名')),
                ('image', models.CharField(max_length=300, verbose_name='教师头像url')),
                ('intro', models.CharField(max_length=200, verbose_name='教师简介')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 't_teacher',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Teacher', verbose_name='主讲老师'),
        ),
    ]
