# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MyCollection')),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Course')),
            ],
        ),
        migrations.AddField(
            model_name='mycollection',
            name='lesson',
            field=models.ManyToManyField(through='user.Relation', to='content.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='mycollection',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
